package model.personalization;

import java.util.ArrayList;
import java.util.List;
import jep.*;
import model.bean.Tag;
import model.bean.User;
import model.dao.TagDAO;
import org.jetbrains.annotations.NotNull;

public class PersonalizationBridge {

    private static final @NotNull JepConfig JEP_CONFIG = new JepConfig();

    static {
        JEP_CONFIG.addIncludePaths("./");
    }

    public PersonalizationBridge() {
        this.dsd = new DatasetSampleDAO();
    }

    /**
     * This method call a python script to register the vote of the user, for the recommended
     * product list generated by the system.
     * Method is synchronized because no more than one user at time may access to the buffer file.
     *
     * @param u the subject user we want to register the vote for the recommended product list
     * @throws VoteRegistrationException if the vote registration fails
     */
    public synchronized void registerVote(@NotNull User u, boolean vote) {
        dsd.doBufferByUsername(u.getUsername()); //scriviamo sul file il campione

        try (Interpreter interp = JEP_CONFIG.createSubInterpreter()) {
            //passiamo il voto da registrare allo script pyhton
            interp.exec("from samplePrediction import registerVote");
            interp.set("vote", vote);
            Boolean success = interp.getValue("registerVote(vote)", Boolean.class);
            interp.close();
            if (!success) {
                throw new VoteRegistrationException();
            }
        } catch (JepException e) {
            throw new VoteRegistrationException(e);
        }
    }

    /**
     * This method queries a python script (and indirectly the machine learning model) to
     * get the tag list for the given user.
     * Method is synchronized because no more than one user at time may access to the buffer file.
     *
     * @param u the subject user we want to get tag list of
     * @return the tag list of the cluster of the user, according to the machine learning model
     * @throws TagPredictionException if the tag prediction fails
     */
    @NotNull
    public synchronized List<Tag> getTagList(@NotNull User u) {
        List<Tag> tags = new ArrayList<>();
        TagDAO td = new TagDAO();
        dsd.doBufferByUsername(u.getUsername()); //scriviamo sul file il campione

        //creiamo l'istanza dell'interprete
        try (Interpreter interp = JEP_CONFIG.createSubInterpreter()) {
            //prendiamoci i tag dallo script python, che chiamerà il modello di machine learning
            interp.exec("from samplePrediction import predict");
            ArrayList<String> tagNames = interp.getValue("predict()", ArrayList.class);
            interp.close();

            //prendiamoci i tag dal database, corrispondenti ai nomi di tag sullo script
            tagNames.forEach(t -> tags.add(td.doRetrieveByName(t)));
            return tags;
        } catch (JepException e) {
            throw new TagPredictionException(e);
        }
    }

    @NotNull
    private final DatasetSampleDAO dsd;
}
